---

swagger: '2.0'
info:
  version: '1.0.0'
  title: Hetula
  description: Secure key-value store for confidential patron information
basePath: /api/v1
schemes: ['https', 'http']

x-cors:
  x-cors-access-control-allow-origin-list: Hetula::Api::V1::corsOriginWhitelist()
  x-cors-access-control-allow-credentials: true
  x-cors-access-control-allow-methods: "*"
  x-cors-access-control-max-age: 3600


### ### DEFINITIONS ### ###
definitions:
  passwordCredentials:
    type: object
    description: Username + password credentials
    required:
      - username
      - password
      - organization
    properties:
      username:
        description: user.username
        type: string
      password:
        description: user.password
        type: string
        format: password
      organization:
        description: organization.name
        type: string


  organization:
    type: object
    description: Organization sharing access to the store
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      createtime:
        type: string
        format: date-time
      updatetime:
        type: string
        format: date-time


  permission:
    type: object
    description: Permission limiting access to the store
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      createtime:
        type: string
        format: date-time
      updatetime:
        type: string
        format: date-time


  ssn:
    type: object
    description: The social security number of a person
    required:
      - ssn
    properties:
      id:
        type: integer
      ssn:
        type: string
      notes:
        description: Free text about anything related to the owner of this SSN.
        type: string
      organizations:
        type: array
        items:
          description: The organization.name
          type: string


  ssnBatchReport:
    type: object
    description: A report of a individual ssn creation inside a big batch operation
    required:
      - ssn
    properties:
      status:
        description: The HTTP status equivalent to what happened to this given ssn. See HTTP response codes for POST /api/v1/ssns for what the status codes mean.
        type: integer
      error:
        description: Textual representation of any errors. If errors are present, the ssn only contains the ssn.ssn, not id.
        type: string
      ssn:
        $ref: '#/definitions/ssn'


  log:
    type: object
    description: A log entry of any DB access
    required:
      - request
      - description
      - ip
      - updatetime
    properties:
      id:
        type: integer
      userid:
        description: The user.id
        type: integer
      organizationid:
        description: The organization.id
        type: integer
      request:
        type: string
      description:
        type: string
      ip:
        description: Where the request originated from
        type: string
      updatetime:
        type: string
        format: date-time


  user:
    type: object
    description: A user of this store, with specific permissions.
    required:
      - realname
      - username
    properties:
      id:
        type: integer
      realname:
        type: string
      username:
        type: string
        format: byte
      password:
        type: string
        format: password
      organizations:
        type: array
        items:
          description: The organization.name
          type: string
      permissions:
        type: array
        items:
          type: string
### END OF ### DEFINITIONS ### ###


### ### PATHS ### ###
paths:
  /oauth/token:
    post:
      summary: OAuth2.0 Token Endpoint
      x-mojo-to: OAuth2#token
      parameters:
        - name: Authorization
          in: header
          type: string
          description: "Basic + the client_name and client_secret concatenated together, separated by ':'. Eg. \"Authorization: Basic KohaFi:$5$Sdgk7UxocfoTbkiY$w1tsJYwyJD4JD8U3w9UM8e7OTOk9oK1oUXb9oBzutM5\""
          format: password
          required: true
        - name: grant_type
          in: formData
          type: string
          description: OAuth2 grant type to use. Use 'password'
          required: true
        - name: username
          in: formData
          type: string
          description: OAuth2 bearer username. MANDATORY if using grant_type=password
          required: false
        - name: password
          in: formData
          type: string
          format: password
          description: OAuth2 bearer password. MANDATORY if using grant_type=password
          required: false
      responses:
        200:
          description: AuthZ succeeded
          headers:
            Cache-Control:
              description: prevent caching!
              type: string
              pattern: no-store
            Pragma:
              description: prevent caching!
              type: string
              pattern: no-cache
          schema:
            type: object
            description: Response with access tokens
            properties:
              access_token:
                description: User session token
                type: string
              token_type:
                description: This is always 'Bearer'
                type: string
                enum:
                  - Bearer
              expires_in:
                description: In how many seconds does this token expire
                type: integer
              refresh_token:
                description: Use this token to refresh the expired access_token
                type: string
                format: password
        400:
          description: AuthZ failed
          headers:
            Cache-Control:
              description: prevent caching!
              type: string
              pattern: no-store
            Pragma:
              description: prevent caching!
              type: string
              pattern: no-cache
          schema:
            type: object
            description: Error description
            required:
              - error
            properties:
              error:
                description: A single ASCII error code
                type: string
              error_description:
                description: Human-readable ASCII text providing additional information, used to assist the client developer in understanding the error that occurred.
                type: string
              error_uri:
                description: A URI identifying a human-readable web page with information about the error
                type: string


  /auth:
    post:
      summary: Authenticate
      x-mojo-to: Authenticate#post
      parameters:
        - name: passwordCredentials
          in: body
          schema:
            $ref: '#/definitions/passwordCredentials'
      responses:
        201:
          description: Session created. Sets the PaStor-cookie to track this session.
        401:
          description: Credentials were not accepted
    get:
      summary: Test the authentication validity
      x-mojo-to: Authenticate#get
      responses:
        204:
          description: Session is still valid
        404:
          description: Session is invalid or not found
    delete:
      summary: Close the current session
      x-mojo-to: Authenticate#delete
      responses:
        204:
          description: Session closed
        404:
          description: Session is invalid or not found


  /organizations:
    get:
      summary: Get all organization
      x-mojo-to: Organizations#list
      responses:
        200:
          description: All organization returned
          schema:
            type: array
            items:
              $ref: '#/definitions/organization'
    post:
      summary: Add a new organization
      x-mojo-to: Organizations#post
      parameters:
        - name: organization
          in: body
          schema:
            $ref: '#/definitions/organization'
      responses:
        201:
          description: Organization added succesfully
          schema:
            $ref: '#/definitions/organization'
        409:
          description: Organization already exists
          schema:
            $ref: '#/definitions/organization'


  /organizations/{id}:
    parameters:
      - name: id
        in: path
        type: integer
        description: organization.id
        required: true
    get:
      summary: Get the organization
      x-mojo-to: Organizations#get
      responses:
        200:
          description: Organization returned
          schema:
            $ref: '#/definitions/organization'
    delete:
      summary: Delete organization
      x-mojo-to: Organizations#delete
      responses:
        204:
          description: Organization deleted succesfully


  /permissions:
    get:
      summary: Get all permissions
      x-mojo-to: Permissions#list
      responses:
        200:
          description: All permissions returned
          schema:
            type: array
            items:
              $ref: '#/definitions/permission'
    post:
      summary: Add a new permission
      x-mojo-to: Permissions#post
      parameters:
        - name: permission
          in: body
          schema:
            $ref: '#/definitions/permission'
      responses:
        201:
          description: permission added successfully
          schema:
            $ref: '#/definitions/permission'
        409:
          description: Permission already exists
          schema:
            $ref: '#/definitions/permission'


  /permissions/{id}:
    parameters:
      - name: id
        in: path
        type: integer
        description: permission.id
        required: true
    get:
      summary: Get the permission
      x-mojo-to: Permissions#get
      responses:
        200:
          description: Permission returned
          schema:
            $ref: '#/definitions/permission'
    delete:
      summary: Delete permission
      x-mojo-to: Permissions#delete
      responses:
        204:
          description: Permission deleted succesfully


  /ssns/{id}:
    parameters:
      - name: id
        in: path
        type: integer
        description: ssn.id
        required: true
    get:
      summary: Get the social security number
      x-mojo-to: Ssns#get
      description: Gain access to a persons ssn using a anonymized ssn-key.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ssn'
    delete:
      summary: Delete ssn
      x-mojo-to: Ssns#delete
      responses:
        204:
          description: Deletion ok


  /ssns:
    get:
      summary: Get all ssns
      x-mojo-to: Ssns#list
      description: Fetch all ssns in the DB, requires a special permission
      responses:
        200:
          description: All ssns returned
          schema:
            type: array
            items:
              $ref: '#/definitions/ssn'
    post:
      summary: Try adding a new ssn
      x-mojo-to: Ssns#post
      description: Used when testing if a patron already has a ssn stored in the current organization. If no ssn existed, an entry is added to DB. If ssn was present in the DB, the ssnkey is returned.
      parameters:
        - name: ssn
          in: body
          schema:
            $ref: '#/definitions/ssn'
      responses:
        201:
          description: SSN created succesfully for this organization
          schema:
            $ref: '#/definitions/ssn'
        200:
          description: SSN already exists but a dependency is added for this organization
          schema:
            $ref: '#/definitions/ssn'
        400:
          description: Ssn is malformed or schema validation error
        409:
          description: Ssn already exists for this given organization
          schema:
            $ref: '#/definitions/ssn'


  /ssns/batch:
    post:
      summary: Add a batch of ssns
      x-mojo-to: Ssns#batch
      description: Add a big batch of ssns and receive reports of the batch operation for each ssn
      parameters:
        - name: ssns
          in: body
          schema:
            type: array
            items:
              description: ssn.ssn
              type: string
      responses:
        200:
          description: Batch operation succeeded
          schema:
            type: array
            items:
              $ref: '#/definitions/ssnBatchReport'


  /ping:
    get:
      summary: Server heartbeat operation
      x-mojo-to: Ping#get
      description: Is the server responding normally
      security: [ ]
      responses:
        204:
          description: OK


  /logs:
    get:
      summary: Read access logs
      x-mojo-to: Logs#list
      parameters:
        - name: since
          description: Inclusive datetime to fetch logs from
          in: query
          type: string
          format: date-time
        - name: until
          description: Inclusive datetime to fetch logs to
          in: query
          type: string
          format: date-time
        - name: userid
          description: Limit results by the given user
          in: query
          type: integer
        - name: organizationid
          description: Limit results by the given organization
          in: query
          type: integer
      responses:
        200:
          description: All log entries narrowed with the given parameters
          schema:
            type: array
            items:
              $ref: '#/definitions/log'


  /users:
    get:
      summary: Get all users
      x-mojo-to: Users#list
      responses:
        200:
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
    post:
      summary: Add a user
      x-mojo-to: Users#post
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/user'
      responses:
        201:
          description: User added
          schema:
            $ref: '#/definitions/user'
        409:
          description: User already exists
          schema:
            $ref: '#/definitions/user'


  /users/{id}:
    parameters:
      - name: id
        in: path
        type: integer
        description: user.id
        required: true
    get:
      summary: Get a user
      x-mojo-to: Users#get
      responses:
        200:
          description: A user
          schema:
            $ref: '#/definitions/user'
    put:
      summary: Modify user
      x-mojo-to: Users#put
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/user'
      responses:
        200:
          description: Modified
          schema:
            $ref: '#/definitions/user'
        404:
          description: User or related permission/organization is not found.
    delete:
      summary: Delete a user
      x-mojo-to: Users#delete
      responses:
        204:
          description: User deleted
### END OF ### PATHS ### ###

security:
  - oauth2password: []

securityDefinitions:
  oauth2password:
    description: Resource Owner Password Credentials Grant
    type: oauth2
    tokenUrl: /api/v1/oauth/token
    flow: password
    scopes:
      get:ssn:  get a ssn
      post:ssn: add a new ssn

